<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return apply_filters(
	'wc_gw_epayco_settings',
	array(
		'enabled'			=> array(
			'title'			=> __( 'Enable/Disable', 'imma' ),
			'label'			=> __( 'Enable Gateway ePayco', 'imma' ),
			'type'			=> 'checkbox',
			'description'	=> '',
			'default'		=> 'no',
		),
		'title'				=> array(
			'title'			=> __( 'Title', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Corresponds to the title that the user sees during checkout.', 'imma' ),
			'default'		=> __( 'Payment Methods via ePayco', 'imma' ),
			'desc_tip'		=> true,
		),
		'description'		=> array(
			'title'			=> __( 'Description', 'imma' ),
			'type'			=> 'textarea',
			'css'			=> 'width: 400px;',
			'description'	=> __( 'Corresponds to the description that the user will see during checkout.', 'imma' ),
			'default'		=> __( 'Pay through your favorite payment methods via ePayco.', 'imma' ),
			'desc_tip'		=> true,
		),
		'logo'				=> array(
			'title'			=> __( 'Logo', 'imma' ),
			'type'			=> 'select',
			'class'			=> 'wc-enhanced-select',
			'description'	=> __( 'This controls the icon/logo which the user sees during checkout.', 'imma' ),
			'default'		=> WCGW_EPAYCO_ASSETS_PATH.'images/epayco_pago_seguro.png',
			'desc_tip'		=> true,
			'options'		=> array(
								WCGW_EPAYCO_ASSETS_PATH.'images/pagos_procesados_por_epayco_260px_.png' => __( 'Option 01', 'imma' ),
								WCGW_EPAYCO_ASSETS_PATH.'images/pagos_procesados_por_epayco_370px_.png' => __( 'Option 02', 'imma' ),
								WCGW_EPAYCO_ASSETS_PATH.'images/epayco_pago_seguro.png' => __( 'Option 03', 'imma' ),
								WCGW_EPAYCO_ASSETS_PATH.'images/epayco_pago_seguro_gray.png' => __( 'Option 04', 'imma' ),
								WCGW_EPAYCO_ASSETS_PATH.'images/logo_epayco_200px.png' => __( 'Option 05', 'imma' ),
								WCGW_EPAYCO_ASSETS_PATH.'images/logo_epayco_400px.png' => __( 'Option 06', 'imma' )
							),
		),
		'reduce_stock'		=> array(
			'title'			=> __( 'Enable/Disable', 'imma' ),
			'label'			=> __( 'Enable Reduce Stock', 'imma' ),
			'type'			=> 'checkbox',
			'description'	=> __( 'By default, once the order is created, the stock of the product is reduced. Regardless of whether the payment is completed correctly or not. Deactivate this option, if only the stock must be reduced when the order is marked as completed.', 'imma' ),
			'default'		=> 'yes',
		),
		'paymentaction' 	=> array(
			'title'			=> __( 'Payment action', 'imma' ),
			'type'			=> 'select',
			'class'			=> 'wc-enhanced-select',
			'description'	=> __( '(Onpage Checkout, the user when paying remains on the site) or (Standart Checkout, the user when paying is redirected to the ePayco gateway).', 'imma' ),
			'default'		=> 'checkout',
			'desc_tip'		=> true,
			'options'		=> array(
								'checkout' => __( 'Standart checkout', 'imma' ),
								'onepage' => __( 'Onepage checkout', 'imma' ),
							),
		),
		'status_completed'   => array(
			'title'       => __( 'Order status for "approved" payments', 'imma' ),
			'type'        => 'select',
			'class'       => 'wc-enhanced-select',
			'description' => __( 'Select the status that will be automatically assigned to orders once payments are approved by the payment gateway.', 'imma' ),
			'default'     => 'wc-completed',
			'desc_tip'    => true,
			'options'     => wc_get_order_statuses(),
		),		
		'lang' 				=> array(
			'title'			=> __( 'Language', 'imma' ),
			'type'			=> 'select',
			'class'			=> 'wc-enhanced-select',
			'description'	=> __( 'This controls the language which the user sees during checkout.', 'imma' ),
			'default'		=> 'ES',
			'desc_tip'		=> true,
			'options'		=> array(
								'ES' => __( 'Spanish', 'imma' ),
								'EN' => __( 'English', 'imma' ),
							),
		),
		'maintenance_task' 	=> array(
			'title'			=> __( 'Enable/Disable', 'imma' ),
			'label'			=> __( 'Order Verification Process (recommended that it be activated)', 'imma' ),
			'type'			=> 'checkbox',
			'description'	=> __( 'Scheduled maintenance task that checks the status of ePayco orders every hour.', 'imma' ),
			'default'		=> 'no',
			'desc_tip'		=> true,
		),		
		'credentials_live' 	=> array(
			'title'			=> __( 'Credentials', 'imma' ),
			'type'			=> 'title',
			'description'	=> __( 'Enter your ePayco account credentials to receive automatic notifications related to transactions received from the platform. Learn how to access your ePayco account credentials.', 'imma' ),
		),		
		'customer_id' 		=> array(
			'title'			=> __( 'Customer ID', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Customer ID (P_CUST_ID_CLIENTE) that identifies you in ePayco. You can find it in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'p_key' 			=> array(
			'title'			=> __( '[live] P_KEY', 'imma' ),
			'type'			=> 'password',
			'description'	=> __( 'Key to sign the information sent and received from ePayco. You can find it in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'test_p_key' 		=> array(
			'title'			=> __( '[test] P_KEY', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Key to sign the information sent and received from ePayco. You can find it in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'public_key' 		=> array(
			'title'			=> __( '[live] Public Key', 'imma' ),
			'type'			=> 'password',
			'description'	=> __( 'Public key to authenticate and consume ePayco services, Provided in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'test_public_key' 	=> array(
			'title'			=> __( '[test] Public Key', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Public key to authenticate and consume ePayco services, Provided in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'secret_key' 		=> array(
			'title'			=> __( '[live] Private Key', 'imma' ),
			'type'			=> 'password',
			'description'	=> __( 'Private key to authenticate and consume ePayco services, Provided in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'test_secret_key' 	=> array(
			'title'			=> __( '[test] Private Key', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Private key to authenticate and consume ePayco services, Provided in your customer panel in the configuration option.', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
		),
		'webhook' 			=> array(
			'title'			=> __( 'Webhook Endpoints', 'imma' ),
			'type'			=> 'title',
			'description'	=> sprintf( __( 'You must add the following webhook endpoint <strong style="background-color:#ddd;">&nbsp;%s&nbsp;</strong> to your account settings</a> (if there isn\'t one already enabled). This will enable you to receive notifications on the charge statuses.', 'imma' ), $this->get_url() ),
		),
		'sandbox' 			=> array(
			'title'			=> __( 'Test mode', 'imma' ),
			'label'			=> __( 'Enable Test Mode', 'imma' ),
			'type'			=> 'checkbox',
			'description'	=> __( 'Place the payment gateway in test mode using test keys.', 'imma' ),
			'default'		=> 'no',
			'desc_tip'		=> true,
		),
		'debug' 			=> array(
			'title'			=> __( 'Logging', 'imma' ),
			'label'			=> __( 'Log debug messages', 'imma' ),
			'type'			=> 'checkbox',
			'description'	=> __( 'Save debug messages to the WooCommerce System Status log.', 'imma' ),
			'default'		=> 'no',
			'desc_tip'		=> true,
		),
		'token' 			=> array(
			'title'			=> __( 'Token', 'imma' ),
			'type'			=> 'text',
			'description'	=> __( 'Token', 'imma' ),
			'default'		=> '',
			'desc_tip'		=> true,
			'disabled' 		=> true,
		),		
	)
);
